Controllers/CreateController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using DatabaseApp.Models;

public class CreateController : Controller
{
    private readonly Database1Context _context;

    public CreateController(Database1Context context)
    {
        _context = context;
    }

    [HttpGet]
    public IActionResult Create()
    {
        return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Create(string supervisorName, string coSupervisorName,string AuthorName,string keywordText,string topicName, string universityName, string instituteName, Thesis thesis)
    {
        if (ModelState.IsValid)
        {
            var supervisor = _context.Supervisors.Include(s => s.Person)
                .FirstOrDefault(s => s.Person.Name == supervisorName);

            if (supervisor == null)
            {
                var newSupervisorPerson = new Person { Name = supervisorName };
                _context.People.Add(newSupervisorPerson);
                _context.SaveChanges();

                supervisor = new Supervisor { PersonId = newSupervisorPerson.PersonId };
                _context.Supervisors.Add(supervisor);
                _context.SaveChanges();
            }

            var coSupervisor = _context.CoSupervisors.Include(cs => cs.Person)
                .FirstOrDefault(cs => cs.Person.Name == coSupervisorName);

            if (coSupervisor == null)
            {
                var newCoSupervisorPerson = new Person { Name = coSupervisorName };
                _context.People.Add(newCoSupervisorPerson);
                _context.SaveChanges();

                coSupervisor = new CoSupervisor { PersonId = newCoSupervisorPerson.PersonId };
                _context.CoSupervisors.Add(coSupervisor);
                _context.SaveChanges();
            }


            var Author= _context.Authors.Include(s => s.Person)
                .FirstOrDefault(a => a.Name == AuthorName);

            if (Author == null)
            {
                var newAuthorPerson = new Person { Name = AuthorName };
                _context.People.Add(newAuthorPerson);
                _context.SaveChanges();
                var newAuthor = new Author
                {
                    Name = AuthorName,
                    PersonId = newAuthorPerson.PersonId
                };

                _context.Authors.Add(newAuthor);
                _context.SaveChanges();
                Author = newAuthor;

            }
            else
            {
                if (Author.Person == null)
                {
                    var newAuthorPerson = new Person { Name = AuthorName };
                    _context.People.Add(newAuthorPerson);
                    _context.SaveChanges();

                    Author.PersonId = newAuthorPerson.PersonId;
                    Author.Person = newAuthorPerson;
                }
                else
                {
                    Author.Person.Name = AuthorName; 
                }

                Author.Name = AuthorName; 
                _context.SaveChanges();
            }
            var keyword = _context.Keywords.FirstOrDefault(k => k.KeywordText == keywordText);
            if (keyword == null)
            {
                var newKeyword = new Keyword { KeywordText = keywordText };
                _context.Keywords.Add(newKeyword);
                _context.SaveChanges();
                keyword = newKeyword;
            }

            var topic = _context.SubjectTopics.FirstOrDefault(t => t.TopicName == topicName);
            if (topic == null)
            {
                var newTopic = new SubjectTopic { TopicName = topicName };
                _context.SubjectTopics.Add(newTopic);
                _context.SaveChanges();
                topic = newTopic;
            }

            var university = _context.Universities.FirstOrDefault(u => u.Name == universityName);
            if (university == null)
            {
                var newUniversity = new University { Name = universityName };
                _context.Universities.Add(newUniversity);
                _context.SaveChanges();
                university = newUniversity;
            }

            var institute = _context.Institutes.FirstOrDefault(i => i.Name == instituteName);
            if (institute == null)
            {
                var newInstitute = new Institute { Name = instituteName, UniversityId = university.UniversityId };
                _context.Institutes.Add(newInstitute);
                _context.SaveChanges();
                institute = newInstitute;
            }

            thesis.SupervisorId = supervisor.SupervisorId;
            thesis.CoSupervisorId = coSupervisor.CoSupervisorId;
            thesis.AuthorId = Author.AuthorId;
            thesis.KeywordId = keyword.KeywordId;
            thesis.TopicId = topic.TopicId;
            thesis.UniversityId = university.UniversityId;
            thesis.InstituteId = institute.InstituteId;

            _context.Theses.Add(thesis);
            _context.SaveChanges();

            return RedirectToAction("Update", "Update"); 
        }

        return View(thesis); 
    }
}

Controllers/UpdateController.cs
using DatabaseApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Query;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using static Microsoft.Extensions.Logging.EventSource.LoggingEventSource;

namespace DatabaseApp.Controllers
{
    public class UpdateController : Controller
    {
        private readonly Database1Context _context;
        private readonly ILogger<HomeController> _logger;

        public UpdateController(Database1Context context, ILogger<HomeController> logger)
        {
            _context = context;
            _logger = logger;
        }

        public IActionResult Update()
        {
            return View("~/Views/Update/UpdateThesis.cshtml");
        }

        public IActionResult Privacy()
        {
            return View();
        }




        [HttpPost]
        public IActionResult SearchByMultipleCriteria(string author, string title, string university, string institute, string language, string supervisor, string keyword, string topic)
        {
            var results = _context.Theses
                .Include(t => t.Author)
                    .ThenInclude(c => c.Person)
                .Include(t => t.University)
                .Include(t => t.Institute)
                .Include(t => t.Supervisor)
                    .ThenInclude(c => c.Person)
                .Include(t => t.CoSupervisor)
                    .ThenInclude(c => c.Person)
                .Include(t => t.Keyword)
                .Include(t => t.Topic);

            var filteredResults = filterThesis(results, author, title, university, institute, language, supervisor, keyword, topic);

            var resultList = filteredResults.ToList();
            ViewBag.Search = "Search by Multiple Criteria";
            return View("UpdateThesis", resultList);
        }



        public static IQueryable<Thesis> filterThesis(IQueryable<Thesis> results, string author, string title, string university, string institute, string language, string supervisor, string keyword, string topic)
        {
            if (results == null)
            {


                return Enumerable.Empty<Thesis>().AsQueryable();
            }

            try
            {
                results = results.Where(t =>
            (string.IsNullOrEmpty(author) || (t.Author.Person.Name.Contains(author))) &&
            (string.IsNullOrEmpty(title) || (t.Title.Contains(title))) &&
            (string.IsNullOrEmpty(university) || (t.University.Name.Contains(university))) &&
            (string.IsNullOrEmpty(institute) || (t.Institute.Name.Contains(institute))) &&
            (string.IsNullOrEmpty(language) || (t.Language.Contains(language))) &&
            (string.IsNullOrEmpty(supervisor) || (t.Supervisor.Person.Name.Contains(supervisor))) &&
            (string.IsNullOrEmpty(keyword) || (t.Keyword.KeywordText.Contains(keyword))) &&
            (string.IsNullOrEmpty(topic) || (t.Topic.TopicName.Contains(topic)))


            );
                return results;
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.ToString());
                return Enumerable.Empty<Thesis>().AsQueryable();
            }
        }

        [HttpPost]
        public IActionResult UpdateThesis(int id, string selectedValue, string newValue)
        {
            var thesisToUpdate = _context.Theses
                .Include(t => t.University)
                .Include(t => t.Institute)
                .Include(t => t.Supervisor)
                            .ThenInclude(s => s.Person)
                .Include(t => t.CoSupervisor)
                .Include(t => t.Keyword)
                .Include(t => t.Topic)
                .FirstOrDefault(t => t.ThesisNumber == id);

            if (thesisToUpdate == null)
            {
                return NotFound();
            }

            if (!string.IsNullOrEmpty(selectedValue) && !string.IsNullOrEmpty(newValue))
            {
                switch (selectedValue)
                {
                    case "University":
                        var existingUniversity = _context.Universities.FirstOrDefault(u => u.Name == newValue);

                        if (existingUniversity == null)
                        {
                            existingUniversity = new University { Name = newValue };
                            _context.Universities.Add(existingUniversity);
                            _context.SaveChanges();

                            thesisToUpdate.UniversityId = existingUniversity.UniversityId;
                        }
                        else
                        {
                            _context.Entry(existingUniversity).State = EntityState.Detached;

                            thesisToUpdate.UniversityId = existingUniversity.UniversityId;
                        }
                        break;
                    case "Keyword":
                        var existingKeyword = _context.Keywords.FirstOrDefault(k => k.KeywordText == newValue);

                        if (existingKeyword == null)
                        {
                            existingKeyword = new Keyword { KeywordText = newValue };
                            _context.Keywords.Add(existingKeyword);
                            _context.SaveChanges();

                            thesisToUpdate.KeywordId = existingKeyword.KeywordId;
                        }
                        else
                        {
                            _context.Entry(existingKeyword).State = EntityState.Detached;
                            thesisToUpdate.KeywordId = existingKeyword.KeywordId;
                        }
                        break;
                    case "Topic":
                        var existingTopic = _context.SubjectTopics.FirstOrDefault(t => t.TopicName == newValue);

                        if (existingTopic == null)
                        {
                            existingTopic = new SubjectTopic { TopicName = newValue };
                            _context.SubjectTopics.Add(existingTopic);
                            _context.SaveChanges();

                            thesisToUpdate.TopicId = existingTopic.TopicId;
                        }
                        else
                        {
                            _context.Entry(existingTopic).State = EntityState.Detached;
                            thesisToUpdate.TopicId = existingTopic.TopicId;
                        }
                        break;
                    case "Institute":
                        var existingInstitute = _context.Institutes.FirstOrDefault(i => i.Name == newValue);

                        if (existingInstitute == null)
                        {
                            existingInstitute = new Institute { Name = newValue };
                            _context.Institutes.Add(existingInstitute);
                            _context.SaveChanges();

                            thesisToUpdate.InstituteId = existingInstitute.InstituteId;
                        }
                        else
                        {
                            _context.Entry(existingInstitute).State = EntityState.Detached;
                            thesisToUpdate.InstituteId = existingInstitute.InstituteId;
                        }
                        break;
                    case "Supervisor":
                        var existingSupervisor = _context.Supervisors
                            .Include(s => s.Person)
                            .FirstOrDefault(s => s.Person != null && s.Person.Name == newValue);

                        if (existingSupervisor == null)
                        {
                            var newPerson = new Person { Name = newValue };
                            var newSupervisor = new Supervisor { Person = newPerson };
                            _context.Supervisors.Add(newSupervisor);
                            _context.SaveChanges();

                            thesisToUpdate.SupervisorId = newSupervisor.SupervisorId;
                        }
                        else
                        {
                            thesisToUpdate.SupervisorId = existingSupervisor.SupervisorId;
                        }
                        break;
                    case "CoSupervisor":
                        var existingCoSupervisor = _context.CoSupervisors
                            .Include(c => c.Person)
                            .FirstOrDefault(c => c.Person != null && c.Person.Name == newValue);

                        if (existingCoSupervisor == null)
                        {
                            var newPerson = new Person { Name = newValue };
                            var newCoSupervisor = new CoSupervisor { Person = newPerson };
                            _context.CoSupervisors.Add(newCoSupervisor);
                            _context.SaveChanges();

                            thesisToUpdate.CoSupervisorId = newCoSupervisor.CoSupervisorId;
                        }
                        else
                        {
                            thesisToUpdate.CoSupervisorId = existingCoSupervisor.CoSupervisorId;
                        }
                        break;


                    default:
                        ModelState.AddModelError(string.Empty, "An invalid value was selected.");
                        return View("UpdateThesis", thesisToUpdate);
                }

                try
                {
                    _context.SaveChanges();
                    return RedirectToAction("UpdateThesis", "thesisToUpdate");
                }
                catch (DbUpdateException ex)
                {
                    ModelState.AddModelError(string.Empty, "An error occurred during the update process: " + ex.Message);

Views/Update/UpdateThesis.cshtml
@model List<DatabaseApp.Models.Thesis>
@{
    ViewData["Title"] = "Update Thesis";
}

<style>
    body {
        background-color: #e0d9c9;
        color: #402b23;
    }

    h1 {
        text-align: center;
        color: #5f4339;
        margin-top: 5px;
    }

    form {
        max-width: 800px;
        margin: 0 auto;
        background: #f2e8da;
        padding: 20px;
        border-radius: 5px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        display: grid;
        grid-template-columns: repeat(4, 1fr);
        gap: 20px;
    }

    label {
        font-size: 16px;
        margin-bottom: 5px;
        color: #5f4339;
    }

    input, select {
        width: 100%;
        padding: 8px;
        box-sizing: border-box;
        margin-bottom: 10px;
        border: 1px solid #5f4339;
        border-radius: 4px;
        font-size: 16px;
    }

    button {
        background-color: #5f4339;
        color: #fff;
        padding: 10px;
        font-size: 16px;
        border: none;
        border-radius: 4px;
        cursor: pointer;
    }

    button:hover {
        background-color: #402b23;
    }

    table {
        width: 100%;
        border-collapse: collapse;
        margin-top: 20px;
    }

    th, td {
        border: 1px solid #5f4339;
        padding: 8px;
        text-align: left;
    }

    th {
        background-color: #5f4339;
        color: #fff;
    }

    tr:nth-child(even) {
        background-color: #f2e8da;
    }

    .modal-content {
        background-color: #fff;
    }

    .modal-title {
        color: #5f4339;
    }

    .modal-body {
        color: #402b23;
    }

    .modal-footer {
        background-color: #f2e8da;
    }

    .create-link {
        text-align: center;
        margin-top: 20px; 
    }

        
        .create-link a {
            color: #5f4339; 
            text-decoration: none;
            font-size: 24px; 
            font-weight: bold;
        }

            .create-link a:hover {
                text-decoration: underline;
                border-bottom: 2px solid #402b23; 
</style>

<h1>@ViewData["Title"]</h1>

<div class= "create-link">
    <a asp-controller="Create" asp-action="Create">Create</a>
</div>

<div>
    <form asp-controller="Update" asp-action="SearchByMultipleCriteria" method="post">
        <label for="author">Search by Author:</label>
        <input type="text" id="author" name="author" />
        
        <label for="title">Search by Title:</label>
        <input type="text" id="title" name="title" />
        
        <label for="university">Search by University:</label>
        <input type="text" id="university" name="university" />
        
        <label for="institute">Search by Institute:</label>
        <input type="text" id="institute" name="institute" />
        
        <label for="language">Search by Language:</label>
        <input type="text" id="language" name="language" />
        
        <label for="supervisor">Search by Supervisor:</label>
        <input type="text" id="supervisor" name="supervisor" />
        
        <label for="keyword">Search by Keyword:</label>
        <input type="text" id="keyword" name="keyword" />
        
        <label for="topic">Search by Topic:</label>
        <input type="text" id="topic" name="topic" />
        
        <button type="submit">Search</button>

    </form>
</div>


@if (ViewBag.Search != null)
{
    <h2>Search Results</h2>
    <p>@ViewBag.Search</p>

    @if (Model != null && Model.Any())
    {
        <table>
            <thead>
                <tr>
                    <th>Başlık</th>
                    <th>Özet</th>
                    <th>Yıl</th>
                    <th>Tür</th>
                    <th>Sayfa Sayısı</th>
                    <th>Dil</th>
                    <th>Teslim Tarihi</th>
                    <th>Yazar</th>
                    <th>Üniversite</th>
                    <th>Enstitü</th>
                    <th>Supervisor</th>
                    <th>Cosupervisor</th>
                    <th>Keyword</th>
                    <th>Topic</th>


                </tr>
            </thead>
            <tbody>
                @foreach (var tez in Model)
                {
                    <tr>
                        <td>@tez.Title</td>
                        <td>@tez.Abstract</td>
                        <td>@tez.Year</td>
                        <td>@tez.Type</td>
                        <td>@tez.NumOfPages</td>
                        <td>@tez.Language</td>
                        <td>@tez.SubmissionDate</td>
                        <td>@(tez.Author != null ? tez.Author.Name : "")</td>
                        <td>@(tez.University != null ? tez.University.Name : "")</td>
                        <td>@(tez.Institute != null ? tez.Institute.Name : "")</td>
                        <td>@(tez.Supervisor != null ? tez.Supervisor.Person?.Name : "")</td>
                        <td>@(tez.CoSupervisor != null ? tez.CoSupervisor.Person?.Name : "")</td>
                        <td>@(tez.Keyword != null ? tez.Keyword.KeywordText : "") </td>>
                        <td>@(tez.Topic != null ? tez.Topic.TopicName : "") </td>>
                        <td>
                            <button type="button" class="btn btn-primary" onclick="openUpdateModal('@tez.ThesisNumber')">Update</button>
                        </td>

                    </tr>
                }
            </tbody>
        </table>
        <div class="modal fade" id="updateModal" tabindex="-1" role="dialog" aria-labelledby="updateModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="updateModalLabel">Tez Güncelleme</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <form id="updateForm" asp-controller="Update" asp-action="UpdateThesis" method="post">
                            <input type="hidden" id="thesisId" name="id" />
                            <div class="form-group">
                                <label for="selectedValue"> Choose the value to update:</label>
                                <select id="selectedValue" name="selectedValue" class="form-control" onchange="toggleNewValueSection(this)">
                                   
                                    <option value="">Seçiniz</option>
                                    <option value="University">Üniversite</option>
                                    <option value="Supervisor">Supervisor</option>
                                    <option value="CoSupervisor">CoSupervisor</option>
                                    <option value="Keyword">Keyword</option>
                                    <option value="Topic">Topic</option>
                                    <option value="Institute">Institute</option>
                                </select>
                            </div>
                            <div class="form-group" id="newValueSection" style="display:none;">
                                <label for="newValue">New value:</label>
                                <input type="text" id="newValue" name="newValue" class="form-control" />
                            </div>
                        </form>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="button" class="btn btn-primary" onclick="submitUpdateForm()">Save</button>
                    </div>
                </div>
            </div>
        </div>

        <script>
            function openUpdateModal(thesisId) {
                $('#updateModal').modal('show');
                $('#thesisId').val(thesisId);
            }

            function submitUpdateForm() {
                var selectedValue = $('#selectedValue').val();
                var newValue = $('#newValue').val();
                var thesisId = $('#thesisId').val();

                $.ajax({
                    type: 'POST',
                    url: '/Update/UpdateThesis',
                    data: {
                        id: thesisId,
                        selectedValue: selectedValue,
                        newValue: newValue
                    },
                    success: function (response) {
                        $('#updateModal').modal('hide'); 
                        location.reload(); 
                    },
                    error: function (error) {
                        console.log(error);
                        $('#updateModal').modal('hide'); 
                    }
                });
            }

            function toggleNewValueSection(select) {
                var selectedValue = $(select).val();
                if (selectedValue !== '') {
                    $('#newValueSection').show();
                } else {
                    $('#newValueSection').hide();
                }
            }
        </script>

        }

}

   